defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_
initialization_network_dir: /home/ggangmei/outputs/1D_PINNs_trainedModel
run_mode: 'eval'

summary_histograms: true
jit: true
save_filetypes : "npz"

scheduler:
  gamma: 0.99998718

optimizer:
  lr: 3.e-4
  betas: [0.9, 0.999]

training:
  rec_validation_freq: 1000
  rec_inference_freq: 1000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 70000

